const cartActionsTypes = {
  TRIGGER_SHOW_CART_DROPDOWN: "TRIGGER_SHOW_CART_DROPDOWN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREMENT_QTY: "INCREMENT_QTY",
  DECREMENT_QTY: "DECREMENT_QTY"
};

export default cartActionsTypes;
